import {
  BadRequestException,
  ConflictException,
  Inject,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { GameTemplate } from '../database/entities/game-template.entity';
import {
  contentTypeFor,
  isAllowedExtension,
  isCompressibleKey,
  slugify,
  TEMPLATE_STORAGE,
} from '../storage/template-storage';
import type { TemplateStorage } from '../storage/template-storage';
import {
  compressAsset,
  sidecarKeyFor,
  SIDECAR_SUFFIX_RE,
} from '../storage/content-encoding';

/** What `POST /templates` returns once a template has been stored. */
export interface UploadTemplateResult {
  id: string;
  path: string;
  files: string[];
}

const INDEX_FILE = 'index.js';

@Injectable()
export class TemplatesService {
  constructor(
    @Inject(TEMPLATE_STORAGE) private readonly storage: TemplateStorage,
    @InjectRepository(GameTemplate)
    private readonly templates: Repository<GameTemplate>,
  ) {}

  /** Lists every registered template (file contents are served separately). */
  listTemplates(): Promise<GameTemplate[]> {
    return this.templates.find();
  }

  /** Returns one template's metadata; throws 404 when it does not exist. */
  async getTemplate(id: string): Promise<GameTemplate> {
    const template = await this.templates.findOneBy({ id });
    if (!template) {
      throw new NotFoundException(`Template not found: ${id}`);
    }
    return template;
  }

  /**
   * Stores an uploaded game template: writes its files under `templates/<slug>/`
   * and registers a {@link GameTemplate} row. Validates the name, the presence of
   * a root-level `index.js`, and that every file is a known web asset.
   */
  async createTemplate(
    name: string,
    files: Express.Multer.File[],
    config?: string,
  ): Promise<UploadTemplateResult> {
    const slug = slugify(name ?? '');
    if (!slug) {
      throw new BadRequestException(
        '`name` is required and must contain letters or digits',
      );
    }

    if (!files || files.length === 0) {
      throw new BadRequestException('At least `index.js` must be uploaded');
    }

    const parsedConfig = this.parseConfig(config);

    // Compute a safe relative key per file and validate it.
    const entries = files.map((file) => ({
      file,
      relKey: this.relKeyFor(file.originalname),
    }));

    const indexCount = entries.filter((e) => e.relKey === INDEX_FILE).length;
    if (indexCount === 0) {
      throw new BadRequestException('A root-level `index.js` file is required');
    }
    if (indexCount > 1) {
      throw new BadRequestException('Only one `index.js` may be uploaded');
    }

    const seen = new Set<string>();
    for (const { relKey } of entries) {
      if (!isAllowedExtension(relKey)) {
        throw new BadRequestException(`Unsupported file type: ${relKey}`);
      }
      // Sidecars are generated below. Accepting an uploaded one would let it
      // shadow a real asset, serving different bytes to compressed and
      // uncompressed clients for the same URL. `isAllowedExtension` also rejects
      // these today, but only because `br`/`gz` happen to be absent from
      // CONTENT_TYPES — this guard states the rule outright.
      if (SIDECAR_SUFFIX_RE.test(relKey)) {
        throw new BadRequestException(
          `Pre-compressed variants are generated by the server: ${relKey}`,
        );
      }
      // Duplicates would silently overwrite each other, and the reported file
      // list would name the key twice.
      if (seen.has(relKey)) {
        throw new BadRequestException(`Duplicate file: ${relKey}`);
      }
      seen.add(relKey);
    }

    if (await this.templates.findOneBy({ id: slug })) {
      throw new ConflictException(`A template named '${slug}' already exists`);
    }

    const path = `templates/${slug}`;
    for (const { file, relKey } of entries) {
      await this.writeAsset(`${path}/${relKey}`, relKey, file.buffer);
    }

    await this.templates.save(
      this.templates.create({ id: slug, path, config: parsedConfig }),
    );

    return { id: slug, path, files: entries.map((e) => e.relKey) };
  }

  /**
   * Writes one uploaded asset, plus its `.br` sidecar when the file type is worth
   * compressing. There is no edge cache in front of this API, so pre-compressing
   * here is what keeps game bundles from going out raw; doing it at upload means
   * each template pays the cost once instead of per request.
   *
   * The content type comes from the key rather than the client's `mimetype`, so
   * stored metadata always matches what the serve path derives.
   */
  private async writeAsset(
    key: string,
    relKey: string,
    body: Buffer,
  ): Promise<void> {
    const contentType = contentTypeFor(relKey);

    if (!isCompressibleKey(relKey)) {
      await this.storage.writeTemplateFile(key, body, { contentType });
      return;
    }

    const compressed = await compressAsset(body);
    // The sidecar is written unconditionally, even for a tiny file where brotli
    // may not be smaller: the serve path infers its existence from the extension,
    // so skipping it would force a storage probe on every request.
    await Promise.all([
      this.storage.writeTemplateFile(key, body, { contentType }),
      this.storage.writeTemplateFile(sidecarKeyFor(key), compressed, {
        contentType,
        contentEncoding: 'br',
      }),
    ]);
  }

  /**
   * Normalises a multipart `originalname` into a safe relative key, preserving a
   * subpath like `assets/app.js` so an uploaded folder tree keeps its shape.
   *
   * The name is untrusted (the upload interceptor sets `preservePath`, so the
   * client chooses it), and this is the only thing standing between it and a
   * storage key. Traversal and drive letters are rejected; a leading slash is
   * stripped rather than refused, since `/assets/app.js` plainly means the
   * template's own root.
   */
  private relKeyFor(originalname: string): string {
    const cleaned = (originalname ?? '')
      .replace(/\\/g, '/')
      .replace(/\/+/g, '/')
      .replace(/^\//, '');
    const segments = cleaned
      .split('/')
      .filter((s) => s.length > 0 && s !== '.');
    if (segments.length === 0 || segments.some((s) => s === '..')) {
      throw new BadRequestException(`Invalid file name: ${originalname}`);
    }
    // A Windows drive letter survives the separator rewrite above (`C:\a\b.js`
    // becomes `C:/a/b.js`), which would create a literal `C:` folder inside the
    // template. It cannot escape the template directory, but it is never what the
    // client meant.
    if (/^[a-z]:$/i.test(segments[0])) {
      throw new BadRequestException(
        `File name must be relative: ${originalname}`,
      );
    }
    return segments.join('/');
  }

  /** Parses the optional `config` JSON string into a plain object (or null). */
  private parseConfig(config?: string): Record<string, unknown> | null {
    if (config == null || config.trim() === '') return null;
    let parsed: unknown;
    try {
      parsed = JSON.parse(config);
    } catch {
      throw new BadRequestException('`config` must be valid JSON');
    }
    if (
      typeof parsed !== 'object' ||
      parsed === null ||
      Array.isArray(parsed)
    ) {
      throw new BadRequestException('`config` must be a JSON object');
    }
    return parsed as Record<string, unknown>;
  }
}
